apiVersion: rules.alerting.grafana.app/v0alpha1
kind: AlertRule
metadata:
  annotations:
    grafana.app/folder: f6hsw6
    grafana.com/provenance: ''
    grafana.com/updateTimestamp: '2026-04-28T08:48:46Z'
    grafana.com/updatedBy: ae5t47muqbegwf
  labels:
    grafana.app/folder: f6hsw6
    grafana.com/group: zero-fly-alerts
    grafana.com/group-index: '1'
  name: dfjn9xellhibka
  namespace: stacks-890472
spec:
  annotations:
    summary: Zero container memory utilization exceeds 90%
  execErrState: Error
  expressions:
    A:
      datasourceUID: afj5re4yk9og0e
      model:
        datasource:
          type: prometheus
          uid: afj5re4yk9og0e
        editorMode: code
        expr: 1 - (fly_instance_memory_mem_available{app=~"production-zero-rm|production-zero-vs"}
          / fly_instance_memory_mem_total{app=~"production-zero-rm|production-zero-vs"})
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: A
      relativeTimeRange:
        from: 10m0s
        to: 0s
    C:
      model:
        conditions:
          - evaluator:
              params:
                - 0.9
              type: gt
            operator:
              type: and
            query:
              params:
                - C
            reducer:
              params: []
              type: last
            type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: C
        type: threshold
      queryType: expression
      source: true
  for: 1m0s
  keepFiringFor: 5m0s
  labels:
    service: zero
    severity: warning
  noDataState: NoData
  title: Flyio zero container memory high
  trigger:
    interval: 1m
