import { atom } from 'tldraw'

// "Threaded object scaling" — a puzzle about a conserved resource that flows
// along threads.
//
// Each node is a circle you can resize by dragging. Nodes are wired together by
// threads. Size is conserved across a connected group, but it doesn't teleport:
// when you grow a node, the size it needs is pulled out of its neighbours, and
// the deficit ripples *outward along the threads* — close nodes give the most,
// distant nodes barely flinch. So the shape of the wiring decides how a pull
// lands, and you solve the board by routing size through the graph.
//
// Targets are generated by replaying real drags from a flat start, so every
// board is solvable by construction — the puzzle is rediscovering a route.

// A node is a circle anchored in place; only its size changes.
export interface Node {
	id: string
	x: number
	y: number
	// `r` is the radius drawn on screen; it eases toward `goal` each tick. The
	// ease speed falls off with `hop`, so a pull travels outward as a wave.
	r: number
	goal: number
	// The radius this node needs to reach to be solved.
	target: number
	// Connected-group index (a conserved pool), assigned from the thread graph.
	group: number
	// Graph distance from the most recently dragged node — drives both the
	// redistribution weight and the ripple timing.
	hop: number
}

// A thread links two nodes and is the path size actually travels along.
export interface Thread {
	a: string
	b: string
}

export interface World {
	nodes: Node[]
	threads: Thread[]
	// Conserved total radius for each group, fixed once the puzzle is built.
	totals: number[]
	grabbedId: string | null
	// Free-running counter for subtle thread shimmer in the overlay.
	t: number
}

// Size limits for a single node and how close counts as solved.
export const MIN_R = 22
export const MAX_R = 150
export const START_R = 64
export const MATCH_TOL = 6

// How sharply a pull's effect falls off per thread-hop when redistributing size.
// Lower = the change stays local to the grabbed node's neighbourhood.
export const HOP_FALLOFF = 0.45
// Ripple feel: nearer nodes ease faster, so a transfer reads as a travelling wave.
export const EASE_BASE = 0.4
export const EASE_FALLOFF = 0.6
export const EASE_MIN = 0.09

// Reactive bridge: bumped every tick so the canvas overlay and HUD re-read the
// imperatively-mutated world.
export const frame$ = atom('ts-frame', 0)

// Two contrasting topologies so the flow rule is legible:
//   - a spine (line of 5): a pull ripples end to end.
//   - a star (hub + 4): a pull at the hub fans out to every spoke at once.
// Positions and wiring only — groups, totals, and targets are filled in by
// initPuzzle() in sim.ts.
function buildWorld(): World {
	const nodes: Node[] = [
		// Spine.
		mkNode('sp-0', -560, -150),
		mkNode('sp-1', -370, -150),
		mkNode('sp-2', -180, -150),
		mkNode('sp-3', 10, -150),
		mkNode('sp-4', 200, -150),
		// Star.
		mkNode('hub', -180, 210),
		mkNode('h-1', -400, 120),
		mkNode('h-2', 40, 120),
		mkNode('h-3', -400, 300),
		mkNode('h-4', 40, 300),
	]
	const threads: Thread[] = [
		{ a: 'sp-0', b: 'sp-1' },
		{ a: 'sp-1', b: 'sp-2' },
		{ a: 'sp-2', b: 'sp-3' },
		{ a: 'sp-3', b: 'sp-4' },
		{ a: 'hub', b: 'h-1' },
		{ a: 'hub', b: 'h-2' },
		{ a: 'hub', b: 'h-3' },
		{ a: 'hub', b: 'h-4' },
	]
	return { nodes, threads, totals: [], grabbedId: null, t: 0 }
}

function mkNode(id: string, x: number, y: number): Node {
	return { id, x, y, r: START_R, goal: START_R, target: START_R, group: -1, hop: 0 }
}

let world = buildWorld()

export function getWorld(): World {
	return world
}

export function resetWorld(): void {
	world = buildWorld()
}

export function publishWorld(): void {
	frame$.set(frame$.get() + 1)
}

export function isMatched(n: Node): boolean {
	return Math.abs(n.r - n.target) <= MATCH_TOL
}

export function matchedCount(): number {
	return world.nodes.filter(isMatched).length
}

export function allMatched(): boolean {
	return world.nodes.every(isMatched)
}
