/**
 * The brand registry. A brand is pure data: a map of CSS custom properties. Two families of
 * token appear in each map:
 *
 * - tldraw's own tokens (`--tl-color-*`, `--tl-radius-*`, `--tlui-cmt-*`), which the commenting
 *   UI already reads — redefining them restyles panels, text, dividers, pills, and markers
 *   without touching a component rule.
 * - Example-level `--brand-*` tokens for what those can't express — fonts, borders, gradients,
 *   pin shapes, letter-spacing — consumed by one generic rule block in brand-themes.css.
 *
 * `brandThemesCss` serializes the registry into the stylesheet the app mounts, scoping each map
 * to `[data-comment-theme='<id>'] [class*='tlui-cmt-']`. The tokens land on the comment elements
 * themselves so they win over the values `.tl-container` defines inside the editor — one
 * mechanism themes both the gallery tiles and the live canvas, and the rest of the tldraw UI
 * keeps its stock look.
 */
export interface BrandTheme {
	id: string
	name: string
	/** One line of positioning, shown under the theme name in the gallery. */
	tagline: string
	/** CSS custom properties, applied to every comment element under this theme. */
	tokens: Record<string, string>
}

/** Serialize the registry into the stylesheet that gets mounted alongside the app. */
export function brandThemesCss(themes: BrandTheme[]): string {
	return themes
		.filter((theme) => Object.keys(theme.tokens).length > 0)
		.map(
			(theme) =>
				`[data-comment-theme='${theme.id}'] [class*='tlui-cmt-'] {\n` +
				Object.entries(theme.tokens)
					.map(([property, value]) => `\t${property}: ${value};`)
					.join('\n') +
				`\n}`
		)
		.join('\n\n')
}

/** Whether a theme reads best over a dark backdrop, derived from its panel color so the gallery
 *  tile floors can't drift out of sync with the palette. */
export function isDarkTheme(theme: BrandTheme): boolean {
	const panel = theme.tokens['--tl-color-panel']
	if (!panel) return false
	const hex = panel.match(/^#([0-9a-f]{6})$/i)
	if (hex) {
		const n = parseInt(hex[1], 16)
		const luma = 0.299 * (n >> 16) + 0.587 * ((n >> 8) & 0xff) + 0.114 * (n & 0xff)
		return luma < 128
	}
	const hsl = panel.match(/^hsla?\([^,]+,[^,]+,\s*([\d.]+)%/)
	if (hsl) return parseFloat(hsl[1]) < 50
	return false
}

export const BRAND_THEMES: BrandTheme[] = [
	{ id: 'tldraw', name: 'tldraw', tagline: 'The default, unthemed experience', tokens: {} },

	{
		id: 'midnight',
		name: 'Midnight',
		tagline: 'Dark, dense, keyboard-first SaaS',
		tokens: {
			'--brand-font':
				"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, sans-serif",
			'--tl-color-panel': '#191921',
			'--tl-color-panel-contrast': '#23232e',
			'--tl-color-text-1': '#e3e3ec',
			'--tl-color-text-2': '#b9b9c6',
			'--tl-color-text-3': '#8b8b9c',
			'--tl-color-divider': '#2b2b38',
			'--tl-color-muted-0': 'hsl(240, 15%, 100%, 3%)',
			'--tl-color-muted-1': 'hsl(240, 15%, 100%, 10%)',
			'--tl-color-muted-2': 'hsl(240, 15%, 100%, 6%)',
			'--tl-color-selected': '#6e79d6',
			'--tl-radius-1': '4px',
			'--tl-radius-2': '6px',
			'--tl-radius-3': '8px',
			'--tl-radius-4': '8px',
			'--tlui-cmt-marker-shadow': '0 2px 8px hsl(240, 40%, 2%, 60%)',
			'--tlui-cmt-pill-shadow': '0 0 0 1px #2b2b38, 0 2px 6px hsl(240, 40%, 2%, 50%)',
			'--tl-shadow-3': '0 0 0 1px #2b2b38, 0 8px 24px hsl(240, 40%, 2%, 60%)',
			'--brand-pin-shape': '8px 8px 8px 0',
			'--brand-pin-bg': '#6e79d6',
			'--brand-reaction-shadow': 'inset 0 0 0 1px #2b2b38',
		},
	},

	{
		id: 'brutalist',
		name: 'Brutalist',
		tagline: 'Thick borders and hard offset shadows',
		tokens: {
			'--brand-font': "'Arial Black', 'Archivo Black', Futura, sans-serif",
			'--tl-color-panel': '#fffdf2',
			'--tl-color-panel-contrast': '#fffdf2',
			'--tl-color-text-1': '#111111',
			'--tl-color-text-2': '#111111',
			'--tl-color-text-3': '#444444',
			'--tl-color-divider': '#111111',
			'--tl-color-muted-0': '#fffdf2',
			'--tl-color-muted-1': '#ffe500',
			'--tl-color-muted-2': '#f4f0dc',
			'--tl-color-selected': '#ff5c00',
			'--tl-radius-1': '0px',
			'--tl-radius-2': '0px',
			'--tl-radius-3': '0px',
			'--tl-radius-4': '0px',
			'--tlui-cmt-marker-shadow': '3px 3px 0 #111111',
			'--tlui-cmt-marker-hover-scale': '1',
			'--tlui-cmt-pill-shadow': '0 0 0 2px #111111',
			'--tl-shadow-3': '6px 6px 0 #111111',
			'--brand-thread-border': '3px solid #111111',
			'--brand-pin-shape': '0',
			'--brand-pin-bg': '#ffe500',
			'--brand-pin-border': '3px solid #111111',
			'--brand-avatar-shape': '0',
			'--brand-author-transform': 'uppercase',
			'--brand-author-spacing': '0.02em',
			'--brand-reaction-border': '2px solid #111111',
			'--brand-reaction-bg': '#fffdf2',
			'--brand-reaction-active-bg': '#ffe500',
			'--brand-field-border': '2px solid #111111',
		},
	},

	{
		id: 'glass',
		name: 'Glass',
		tagline: 'Frosted translucent panels',
		tokens: {
			'--brand-font': "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
			'--tl-color-panel': 'hsla(0, 0%, 100%, 0.62)',
			'--tl-color-panel-contrast': 'hsla(0, 0%, 100%, 0.9)',
			'--tl-color-text-1': '#1c1c2e',
			'--tl-color-text-2': '#3d3d55',
			'--tl-color-text-3': '#6d6d88',
			'--tl-color-divider': 'hsla(240, 30%, 40%, 0.18)',
			'--tl-color-muted-0': 'hsla(0, 0%, 100%, 0.35)',
			'--tl-color-muted-1': 'hsla(240, 30%, 40%, 0.16)',
			'--tl-color-muted-2': 'hsla(240, 30%, 40%, 0.09)',
			'--tl-color-selected': '#4a7dff',
			'--tl-radius-1': '8px',
			'--tl-radius-2': '10px',
			'--tl-radius-3': '14px',
			'--tl-radius-4': '18px',
			'--tlui-cmt-marker-shadow': '0 4px 16px hsla(240, 40%, 30%, 0.25)',
			'--tlui-cmt-pill-shadow':
				'0 0 0 1px hsla(0, 0%, 100%, 0.6), 0 4px 12px hsla(240, 40%, 30%, 0.15)',
			'--tl-shadow-3': '0 0 0 1px hsla(0, 0%, 100%, 0.65), 0 12px 40px hsla(240, 40%, 30%, 0.28)',
			'--brand-backdrop': 'blur(14px) saturate(1.4)',
			'--brand-chrome-backdrop': 'blur(10px)',
			'--brand-pin-bg': 'hsla(0, 0%, 100%, 0.7)',
			'--brand-pin-border': '1px solid hsla(0, 0%, 100%, 0.8)',
			'--brand-pin-backdrop': 'blur(8px)',
		},
	},

	{
		id: 'terminal',
		name: 'Terminal',
		tagline: 'Phosphor green on black, monospace',
		tokens: {
			'--brand-font': "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Courier New', monospace",
			'--tl-color-panel': '#050a06',
			'--tl-color-panel-contrast': '#0a140c',
			'--tl-color-text-1': '#33ff66',
			'--tl-color-text-2': '#2ad956',
			'--tl-color-text-3': '#1e9c42',
			'--tl-color-divider': '#14522a',
			'--tl-color-muted-0': 'hsla(140, 100%, 60%, 0.04)',
			'--tl-color-muted-1': 'hsla(140, 100%, 60%, 0.16)',
			'--tl-color-muted-2': 'hsla(140, 100%, 60%, 0.08)',
			'--tl-color-selected': '#33ff66',
			'--tl-radius-1': '0px',
			'--tl-radius-2': '0px',
			'--tl-radius-3': '0px',
			'--tl-radius-4': '0px',
			'--tlui-cmt-marker-shadow': '0 0 10px hsla(140, 100%, 60%, 0.45)',
			'--tlui-cmt-pill-shadow': '0 0 0 1px #14522a',
			'--tl-shadow-3': '0 0 0 1px #33ff66, 0 0 18px hsla(140, 100%, 60%, 0.35)',
			'--brand-pin-shape': '0',
			'--brand-pin-bg': '#050a06',
			'--brand-pin-border': '1px solid #33ff66',
			'--brand-avatar-shape': '0',
			'--brand-author-transform': 'uppercase',
			'--brand-author-prefix': "'> '",
			'--brand-author-prefix-color': '#1e9c42',
			'--brand-reaction-border': '1px solid #14522a',
			'--brand-reaction-bg': 'transparent',
		},
	},

	{
		id: 'candy',
		name: 'Candy',
		tagline: 'Pastel pinks, maximum roundness',
		tokens: {
			'--brand-font':
				"ui-rounded, 'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Quicksand, 'Segoe UI', sans-serif",
			'--tl-color-panel': '#fff2f8',
			'--tl-color-panel-contrast': '#ffffff',
			'--tl-color-text-1': '#6b2d5c',
			'--tl-color-text-2': '#93487f',
			'--tl-color-text-3': '#c286ad',
			'--tl-color-divider': '#ffd3e8',
			'--tl-color-muted-0': '#ffe9f3',
			'--tl-color-muted-1': '#ffc9e2',
			'--tl-color-muted-2': '#ffe1ef',
			'--tl-color-selected': '#ff5ca8',
			'--tl-radius-1': '10px',
			'--tl-radius-2': '14px',
			'--tl-radius-3': '18px',
			'--tl-radius-4': '22px',
			'--tlui-cmt-marker-shadow': '0 4px 12px hsla(330, 100%, 68%, 0.4)',
			'--tlui-cmt-pill-shadow': '0 0 0 2px #ffd3e8, 0 4px 10px hsla(330, 100%, 68%, 0.2)',
			'--tl-shadow-3': '0 0 0 2px #ffd3e8, 0 10px 28px hsla(330, 100%, 68%, 0.3)',
			'--brand-pin-shape': '50%',
			'--brand-pin-bg': '#ff5ca8',
			'--brand-pin-border': '2px solid #ffffff',
		},
	},

	{
		id: 'enterprise',
		name: 'Enterprise',
		tagline: 'Buttoned-up corporate blue',
		tokens: {
			'--brand-font': "'Segoe UI', Tahoma, Arial, sans-serif",
			'--tl-color-panel': '#ffffff',
			'--tl-color-panel-contrast': '#ffffff',
			'--tl-color-text-1': '#1f2a44',
			'--tl-color-text-2': '#445069',
			'--tl-color-text-3': '#64748b',
			'--tl-color-divider': '#d8dee9',
			'--tl-color-muted-0': '#f6f8fb',
			'--tl-color-muted-1': '#dbe4f0',
			'--tl-color-muted-2': '#eef2f7',
			'--tl-color-selected': '#0b5fff',
			'--tl-radius-1': '3px',
			'--tl-radius-2': '4px',
			'--tl-radius-3': '4px',
			'--tl-radius-4': '4px',
			'--tlui-cmt-marker-shadow': '0 1px 3px hsla(220, 40%, 20%, 0.3)',
			'--tlui-cmt-pill-shadow': '0 0 0 1px #d8dee9, 0 1px 3px hsla(220, 40%, 20%, 0.08)',
			'--tl-shadow-3': '0 0 0 1px #d8dee9, 0 4px 14px hsla(220, 40%, 20%, 0.12)',
			'--brand-thread-border-top': '3px solid #0b5fff',
			'--brand-pin-shape': '4px 4px 4px 0',
			'--brand-pin-bg': '#0b5fff',
			'--brand-avatar-shape': '4px',
			'--brand-author-weight': '700',
		},
	},

	{
		id: 'editorial',
		name: 'Editorial',
		tagline: 'Newsprint serif with hairline rules',
		tokens: {
			'--brand-font': "Georgia, 'Times New Roman', Times, serif",
			'--tl-color-panel': '#faf7f0',
			'--tl-color-panel-contrast': '#faf7f0',
			'--tl-color-text-1': '#1a1a1a',
			'--tl-color-text-2': '#3c3830',
			'--tl-color-text-3': '#6b6459',
			'--tl-color-divider': '#c9c2b4',
			'--tl-color-muted-0': '#f3efe5',
			'--tl-color-muted-1': '#ded7c6',
			'--tl-color-muted-2': '#efeadd',
			'--tl-color-selected': '#8c1c13',
			'--tl-radius-1': '0px',
			'--tl-radius-2': '0px',
			'--tl-radius-3': '0px',
			'--tl-radius-4': '0px',
			'--tlui-cmt-marker-shadow': '0 2px 5px hsla(40, 20%, 20%, 0.3)',
			'--tlui-cmt-pill-shadow': '0 0 0 1px #1a1a1a',
			'--tl-shadow-3': '0 0 0 1px #1a1a1a, 0 6px 18px hsla(40, 20%, 20%, 0.18)',
			'--brand-thread-border-top': '4px double #1a1a1a',
			'--brand-pin-bg': '#faf7f0',
			'--brand-pin-border': '1.5px solid #1a1a1a',
			'--brand-author-variant': 'small-caps',
			'--brand-author-spacing': '0.04em',
			'--brand-author-size': '13px',
			'--brand-time-style': 'italic',
			'--brand-text-size': '13px',
			'--brand-text-leading': '1.55',
		},
	},

	{
		id: 'sticky',
		name: 'Sticky note',
		tagline: 'Paper yellow with a handwritten voice',
		tokens: {
			'--brand-font': "'Comic Sans MS', 'Marker Felt', 'Segoe Print', cursive",
			'--tl-color-panel': '#fff6a9',
			'--tl-color-panel-contrast': '#fffbcf',
			'--tl-color-text-1': '#4a3b0a',
			'--tl-color-text-2': '#6e5a15',
			'--tl-color-text-3': '#94803d',
			'--tl-color-divider': 'hsla(48, 70%, 20%, 0.25)',
			'--tl-color-muted-0': 'hsla(0, 0%, 100%, 0.45)',
			'--tl-color-muted-1': 'hsla(48, 70%, 20%, 0.18)',
			'--tl-color-muted-2': 'hsla(48, 70%, 20%, 0.09)',
			'--tl-color-selected': '#d97706',
			'--tl-radius-1': '2px',
			'--tl-radius-2': '2px',
			'--tl-radius-3': '2px',
			'--tl-radius-4': '2px',
			'--tlui-cmt-marker-shadow': '1px 3px 6px hsla(48, 70%, 20%, 0.35)',
			'--tlui-cmt-pill-shadow':
				'0 0 0 1px hsla(48, 70%, 20%, 0.25), 1px 2px 4px hsla(48, 70%, 20%, 0.2)',
			'--tl-shadow-3': '1px 6px 16px hsla(48, 70%, 20%, 0.35)',
			'--brand-thread-tilt': '-0.6deg',
			'--brand-pin-shape': '2px',
			'--brand-pin-bg': '#fff6a9',
			'--brand-pin-border': '1.5px solid #4a3b0a',
			'--brand-pin-tilt': '3deg',
			'--brand-avatar-shape': '4px',
			'--brand-avatar-tilt': '-4deg',
		},
	},

	{
		id: 'neon',
		name: 'Neon',
		tagline: 'Cyberpunk magenta and cyan glow',
		tokens: {
			'--brand-font': "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
			'--tl-color-panel': '#0d0221',
			'--tl-color-panel-contrast': '#1a0b38',
			'--tl-color-text-1': '#f0e6ff',
			'--tl-color-text-2': '#c4afe8',
			'--tl-color-text-3': '#9d8ac7',
			'--tl-color-divider': 'hsla(315, 100%, 59%, 0.35)',
			'--tl-color-muted-0': 'hsla(315, 100%, 59%, 0.06)',
			'--tl-color-muted-1': 'hsla(315, 100%, 59%, 0.25)',
			'--tl-color-muted-2': 'hsla(315, 100%, 59%, 0.12)',
			'--tl-color-selected': '#00f0ff',
			'--tl-radius-1': '6px',
			'--tl-radius-2': '8px',
			'--tl-radius-3': '10px',
			'--tl-radius-4': '12px',
			'--tlui-cmt-marker-shadow': '0 0 12px hsla(315, 100%, 59%, 0.6)',
			'--tlui-cmt-pill-shadow':
				'0 0 0 1px hsla(315, 100%, 59%, 0.5), 0 0 10px hsla(315, 100%, 59%, 0.35)',
			'--tl-shadow-3':
				'0 0 0 1px #ff2ec4, 0 0 20px hsla(315, 100%, 59%, 0.45), 0 0 60px hsla(187, 100%, 50%, 0.15)',
			'--brand-pin-bg': 'linear-gradient(135deg, #ff2ec4, #00f0ff)',
			'--brand-author-color': '#00f0ff',
			'--brand-author-transform': 'uppercase',
			'--brand-author-spacing': '0.06em',
			'--brand-author-size': '11px',
			'--brand-reaction-active-bg': 'hsla(187, 100%, 50%, 0.2)',
			'--brand-reaction-active-shadow': '0 0 8px hsla(187, 100%, 50%, 0.5)',
		},
	},

	{
		id: 'pixel',
		name: 'Pixel',
		tagline: '8-bit arcade chrome, zero curves',
		tokens: {
			'--brand-font': "'Courier New', Courier, monospace",
			'--tl-color-panel': '#e8e8d0',
			'--tl-color-panel-contrast': '#e8e8d0',
			'--tl-color-text-1': '#202020',
			'--tl-color-text-2': '#202020',
			'--tl-color-text-3': '#606050',
			'--tl-color-divider': '#202020',
			'--tl-color-muted-0': '#dcdcc2',
			'--tl-color-muted-1': '#b8b89a',
			'--tl-color-muted-2': '#d4d4b8',
			'--tl-color-selected': '#d03030',
			'--tl-radius-1': '0px',
			'--tl-radius-2': '0px',
			'--tl-radius-3': '0px',
			'--tl-radius-4': '0px',
			'--tlui-cmt-marker-shadow': '2px 2px 0 #202020',
			'--tlui-cmt-marker-hover-scale': '1',
			'--tlui-cmt-marker-transition': '0s',
			'--tlui-cmt-pill-shadow': '0 0 0 2px #202020',
			'--tl-shadow-3': '4px 4px 0 #202020',
			'--brand-thread-border': '4px solid #202020',
			'--brand-body-weight': '700',
			'--brand-pin-shape': '0',
			'--brand-pin-bg': '#d03030',
			'--brand-pin-border': '3px solid #202020',
			'--brand-avatar-shape': '0',
			'--brand-author-transform': 'uppercase',
			'--brand-reaction-border': '2px solid #202020',
			'--brand-reaction-bg': '#e8e8d0',
		},
	},

	{
		id: 'luxe',
		name: 'Luxe',
		tagline: 'Black and gold, wide letter-spacing',
		tokens: {
			'--brand-font': "Didot, 'Bodoni MT', Georgia, serif",
			'--tl-color-panel': '#0e0d0b',
			'--tl-color-panel-contrast': '#1c1a15',
			'--tl-color-text-1': '#f5e9cf',
			'--tl-color-text-2': '#d9c69c',
			'--tl-color-text-3': '#a08d64',
			'--tl-color-divider': '#2e2921',
			'--tl-color-muted-0': 'hsla(45, 60%, 80%, 0.04)',
			'--tl-color-muted-1': 'hsla(45, 60%, 80%, 0.16)',
			'--tl-color-muted-2': 'hsla(45, 60%, 80%, 0.08)',
			'--tl-color-selected': '#d4af37',
			'--tl-radius-1': '2px',
			'--tl-radius-2': '2px',
			'--tl-radius-3': '2px',
			'--tl-radius-4': '2px',
			'--tlui-cmt-marker-shadow': '0 3px 10px hsla(0, 0%, 0%, 0.6)',
			'--tlui-cmt-pill-shadow': '0 0 0 1px #d4af37',
			'--tl-shadow-3': '0 0 0 1px #d4af37, 0 10px 30px hsla(0, 0%, 0%, 0.6)',
			'--brand-pin-shape': '50%',
			'--brand-pin-bg': '#0e0d0b',
			'--brand-pin-border': '1px solid #d4af37',
			'--brand-author-transform': 'uppercase',
			'--brand-author-spacing': '0.14em',
			'--brand-author-size': '10px',
			'--brand-author-weight': '400',
			'--brand-time-size': '10px',
			'--brand-time-spacing': '0.06em',
		},
	},

	{
		id: 'forest',
		name: 'Forest',
		tagline: 'Botanical greens, organic shapes',
		tokens: {
			'--brand-font': "'Palatino Linotype', Palatino, 'Book Antiqua', Georgia, serif",
			'--tl-color-panel': '#f3f7ee',
			'--tl-color-panel-contrast': '#ffffff',
			'--tl-color-text-1': '#24371f',
			'--tl-color-text-2': '#40573a',
			'--tl-color-text-3': '#6f855f',
			'--tl-color-divider': '#d5e3c8',
			'--tl-color-muted-0': '#ebf2e2',
			'--tl-color-muted-1': '#c9dbb6',
			'--tl-color-muted-2': '#e2ecd6',
			'--tl-color-selected': '#3f7d2c',
			'--tl-radius-1': '8px',
			'--tl-radius-2': '10px',
			'--tl-radius-3': '14px',
			'--tl-radius-4': '18px',
			'--tlui-cmt-marker-shadow': '0 3px 8px hsla(105, 30%, 25%, 0.3)',
			'--tlui-cmt-pill-shadow': '0 0 0 1px #d5e3c8, 0 2px 6px hsla(105, 30%, 25%, 0.12)',
			'--tl-shadow-3': '0 0 0 1px #d5e3c8, 0 8px 22px hsla(105, 30%, 25%, 0.18)',
			'--brand-thread-radius': '20px 6px 20px 6px',
			'--brand-pin-shape': '0 50% 50% 50%',
			'--brand-pin-bg': '#3f7d2c',
			'--brand-avatar-shape': '40% 60% 55% 45%',
		},
	},

	{
		id: 'blueprint',
		name: 'Blueprint',
		tagline: 'Drafting-table blue with dashed lines',
		tokens: {
			'--brand-font': 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
			'--tl-color-panel': '#0a3d62',
			'--tl-color-panel-contrast': '#0f4c78',
			'--tl-color-text-1': '#eaf6ff',
			'--tl-color-text-2': '#bcdcf2',
			'--tl-color-text-3': '#7fb3d5',
			'--tl-color-divider': 'hsla(204, 100%, 96%, 0.35)',
			'--tl-color-muted-0': 'hsla(204, 100%, 96%, 0.05)',
			'--tl-color-muted-1': 'hsla(204, 100%, 96%, 0.2)',
			'--tl-color-muted-2': 'hsla(204, 100%, 96%, 0.1)',
			'--tl-color-selected': '#ffd166',
			'--tl-radius-1': '0px',
			'--tl-radius-2': '0px',
			'--tl-radius-3': '0px',
			'--tl-radius-4': '0px',
			'--tlui-cmt-marker-shadow': '0 2px 8px hsla(205, 80%, 10%, 0.5)',
			'--tlui-cmt-pill-shadow': '0 0 0 1px hsla(204, 100%, 96%, 0.5)',
			'--tl-shadow-3': '0 8px 24px hsla(205, 80%, 10%, 0.45)',
			'--brand-thread-border': '1px dashed hsla(204, 100%, 96%, 0.65)',
			'--brand-thread-outline': '1px solid hsla(204, 100%, 96%, 0.25)',
			'--brand-thread-outline-offset': '3px',
			'--brand-pin-shape': '50%',
			'--brand-pin-bg': '#0a3d62',
			'--brand-pin-border': '1px dashed #eaf6ff',
			'--brand-author-transform': 'uppercase',
			'--brand-author-spacing': '0.08em',
			'--brand-author-size': '10px',
			'--brand-reaction-border': '1px dashed hsla(204, 100%, 96%, 0.5)',
			'--brand-reaction-bg': 'transparent',
		},
	},

	{
		id: 'comic',
		name: 'Comic',
		tagline: 'Speech bubbles with ink outlines',
		tokens: {
			'--brand-font': "'Comic Sans MS', 'Chalkboard SE', 'Segoe Print', cursive",
			'--tl-color-panel': '#fffef5',
			'--tl-color-panel-contrast': '#ffffff',
			'--tl-color-text-1': '#14213d',
			'--tl-color-text-2': '#2b3a5e',
			'--tl-color-text-3': '#5c6b8c',
			'--tl-color-divider': '#14213d',
			'--tl-color-muted-0': '#fff8e0',
			'--tl-color-muted-1': '#ffe8b0',
			'--tl-color-muted-2': '#fff3cf',
			'--tl-color-selected': '#fca311',
			'--tl-radius-1': '10px',
			'--tl-radius-2': '12px',
			'--tl-radius-3': '16px',
			'--tl-radius-4': '18px',
			'--tlui-cmt-marker-shadow': '3px 3px 0 rgba(20, 33, 61, 0.9)',
			'--tlui-cmt-pill-shadow': '0 0 0 2px #14213d',
			'--tl-shadow-3': '0 0 0 3px #14213d, 6px 6px 0 rgba(20, 33, 61, 0.9)',
			'--brand-tail': 'block',
			'--brand-tail-color': '#14213d',
			'--brand-pin-bg': '#fca311',
			'--brand-pin-border': '3px solid #14213d',
			'--brand-author-transform': 'uppercase',
			'--brand-author-weight': '700',
			'--brand-reaction-border': '2px solid #14213d',
			'--brand-reaction-bg': '#fffef5',
		},
	},

	{
		id: 'nordic',
		name: 'Nordic',
		tagline: 'Airy, muted, quietly minimal',
		tokens: {
			'--brand-font': "'Helvetica Neue', Helvetica, Arial, sans-serif",
			'--tl-color-panel': '#fbfbf9',
			'--tl-color-panel-contrast': '#ffffff',
			'--tl-color-text-1': '#3d4247',
			'--tl-color-text-2': '#5b6167',
			'--tl-color-text-3': '#9aa2a9',
			'--tl-color-divider': '#eceae5',
			'--tl-color-muted-0': '#f5f4f0',
			'--tl-color-muted-1': '#e3e1da',
			'--tl-color-muted-2': '#f0efe9',
			'--tl-color-selected': '#7d9c8d',
			'--tl-radius-1': '8px',
			'--tl-radius-2': '10px',
			'--tl-radius-3': '12px',
			'--tl-radius-4': '14px',
			'--tlui-cmt-thread-padding': '16px',
			'--tlui-cmt-marker-shadow': '0 4px 14px hsla(210, 8%, 30%, 0.18)',
			'--tlui-cmt-pill-shadow': '0 2px 10px hsla(210, 8%, 30%, 0.1)',
			'--tl-shadow-3': '0 12px 40px hsla(210, 8%, 30%, 0.12)',
			'--brand-pin-shape': '50%',
			'--brand-pin-bg': '#7d9c8d',
			'--brand-author-weight': '500',
			'--brand-author-spacing': '0.01em',
		},
	},

	{
		id: 'sunset',
		name: 'Sunset',
		tagline: 'Vaporwave gradients',
		tokens: {
			'--brand-font': "Verdana, Geneva, 'DejaVu Sans', sans-serif",
			'--tl-color-panel': '#45276b',
			'--tl-color-panel-contrast': '#5b3690',
			'--tl-color-text-1': '#ffffff',
			'--tl-color-text-2': 'hsla(0, 0%, 100%, 0.85)',
			'--tl-color-text-3': 'hsla(0, 0%, 100%, 0.65)',
			'--tl-color-divider': 'hsla(0, 0%, 100%, 0.25)',
			'--tl-color-muted-0': 'hsla(0, 0%, 100%, 0.08)',
			'--tl-color-muted-1': 'hsla(0, 0%, 100%, 0.28)',
			'--tl-color-muted-2': 'hsla(0, 0%, 100%, 0.16)',
			'--tl-color-selected': '#ffd166',
			'--tl-radius-1': '8px',
			'--tl-radius-2': '10px',
			'--tl-radius-3': '12px',
			'--tl-radius-4': '14px',
			'--tlui-cmt-marker-shadow': '0 4px 14px hsla(330, 80%, 40%, 0.5)',
			'--tlui-cmt-pill-shadow':
				'0 0 0 1px hsla(0, 0%, 100%, 0.3), 0 4px 10px hsla(280, 60%, 20%, 0.4)',
			'--tl-shadow-3': '0 12px 36px hsla(280, 60%, 15%, 0.55)',
			'--brand-thread-bg': 'linear-gradient(160deg, #3b1d60 0%, #764ba2 55%, #ff6b9d 130%)',
			'--brand-pin-bg': 'linear-gradient(160deg, #764ba2, #ff6b9d)',
		},
	},

	{
		id: 'crayon',
		name: 'Crayon',
		tagline: 'Primary colors, playroom energy',
		tokens: {
			'--brand-font': "'Chalkboard SE', 'Comic Sans MS', 'Segoe Print', cursive",
			'--tl-color-panel': '#ffffff',
			'--tl-color-panel-contrast': '#ffffff',
			'--tl-color-text-1': '#333333',
			'--tl-color-text-2': '#4d4d4d',
			'--tl-color-text-3': '#8c8c8c',
			'--tl-color-divider': '#bfd7ea',
			'--tl-color-muted-0': '#fdf6e3',
			'--tl-color-muted-1': '#ffe66d',
			'--tl-color-muted-2': '#fff3b8',
			'--tl-color-selected': '#e63946',
			'--tl-radius-1': '8px',
			'--tl-radius-2': '10px',
			'--tl-radius-3': '12px',
			'--tl-radius-4': '14px',
			'--tlui-cmt-marker-shadow': '0 3px 8px hsla(0, 0%, 0%, 0.25)',
			'--tlui-cmt-pill-shadow': '0 0 0 2px #1d3557, 0 2px 6px hsla(0, 0%, 0%, 0.12)',
			'--tl-shadow-3': '0 6px 18px hsla(0, 0%, 0%, 0.18)',
			'--brand-thread-border': '3px dashed #e63946',
			'--brand-pin-shape': '50%',
			'--brand-pin-bg': '#457b9d',
			'--brand-pin-border': '3px solid #ffe66d',
			'--brand-author-color': '#e63946',
			'--brand-reaction-border': '2px solid #1d3557',
			'--brand-reaction-bg': '#ffe66d',
		},
	},
]
