// Generated by `yarn gen-controls` from component Props types. Do not edit.
// Regenerate when a sketchbook component's props change.
import { ArgType } from './sketch'

export const autoArgTypes: Record<string, Record<string, ArgType>> = {
	'sketchbooks/anchoring/comment-anchor.sketchbook.tsx': {
		anchor: {
			control: 'text',
		},
		open: {
			control: 'boolean',
		},
	},
	'sketchbooks/comments/anchored-comment.sketchbook.tsx': {
		comments: {
			control: 'text',
		},
		open: {
			control: 'boolean',
		},
		thread: {
			control: 'text',
		},
	},
	'sketchbooks/comments/avatar.sketchbook.tsx': {
		name: {
			control: 'text',
		},
	},
	'sketchbooks/comments/byline.sketchbook.tsx': {
		author: {
			control: 'text',
		},
		date: {
			control: 'text',
		},
		edited: {
			control: 'boolean',
		},
	},
	'sketchbooks/comments/comment-card.sketchbook.tsx': {
		author: {
			control: 'text',
		},
		body: {
			control: 'text',
		},
		date: {
			control: 'text',
		},
		edited: {
			control: 'boolean',
		},
		you: {
			control: 'boolean',
		},
	},
	'sketchbooks/comments/comment-composer.sketchbook.tsx': {
		author: {
			control: 'text',
		},
		placeholder: {
			control: 'text',
		},
	},
	'sketchbooks/comments/comment-pin.sketchbook.tsx': {
		number: {
			control: 'number',
		},
		open: {
			control: 'boolean',
		},
		resolved: {
			control: 'boolean',
		},
	},
	'sketchbooks/comments/comment-text.sketchbook.tsx': {
		text: {
			control: 'text',
		},
	},
	'sketchbooks/comments/comment-thread.sketchbook.tsx': {
		resolved: {
			control: 'boolean',
		},
	},
	'sketchbooks/comments/comments-sidebar.sketchbook.tsx': {
		empty: {
			control: 'boolean',
		},
	},
	'sketchbooks/comments/empty-state.sketchbook.tsx': {
		message: {
			control: 'text',
		},
	},
	'sketchbooks/comments/mention.sketchbook.tsx': {
		name: {
			control: 'text',
		},
	},
	'sketchbooks/comments/reaction.sketchbook.tsx': {
		active: {
			control: 'boolean',
		},
		count: {
			control: 'number',
		},
		emoji: {
			control: 'text',
		},
	},
	'sketchbooks/comments/send-button.sketchbook.tsx': {
		disabled: {
			control: 'boolean',
		},
		label: {
			control: 'text',
		},
	},
	'sketchbooks/editor-probe.sketchbook.tsx': {
		label: {
			control: 'text',
		},
	},
	'sketchbooks/flows/canvas-with-comments.sketchbook.tsx': {
		empty: {
			control: 'boolean',
		},
	},
	'sketchbooks/flows/canvas-without-comments.sketchbook.tsx': {
		empty: {
			control: 'boolean',
		},
	},
}
