// This file is auto-generated. Do not edit it directly.
// Instead, edit the fetchEverythingSql.test.ts file and run yarn test -u

export const fetchEverythingSql = `
WITH
  my_owned_files AS (SELECT * FROM public."file" WHERE "ownerId" = $1),
  my_file_states AS (SELECT * FROM public."file_state" WHERE "userId" = $1),
  files_shared_with_me AS (SELECT f.* FROM my_file_states ufs JOIN public."file" f ON f.id = ufs."fileId" WHERE ufs."isFileOwner" = false AND f.shared = true),
  all_files AS (SELECT * FROM my_owned_files UNION SELECT * FROM files_shared_with_me)
SELECT
  'user' as "table",
  "allowAnalyticsCookie"::boolean as "0",
  "areKeyboardShortcutsEnabled"::boolean as "1",
  "enhancedA11yMode"::boolean as "2",
  "exportBackground"::boolean as "3",
  "exportPadding"::boolean as "4",
  "isDynamicSizeMode"::boolean as "5",
  "isPasteAtCursorMode"::boolean as "6",
  "isSnapMode"::boolean as "7",
  "isWrapMode"::boolean as "8",
  "animationSpeed"::bigint as "9",
  "createdAt"::bigint as "10",
  "edgeScrollSpeed"::bigint as "11",
  "updatedAt"::bigint as "12",
  "avatar"::text as "13",
  "color"::text as "14",
  "colorScheme"::text as "15",
  "email"::text as "16",
  "exportFormat"::text as "17",
  "exportTheme"::text as "18",
  "flags"::text as "19",
  "id"::text as "20",
  "inputMode"::text as "21",
  "locale"::text as "22",
  "name"::text as "23"
FROM public."user"
WHERE "id" = $1
UNION ALL
SELECT
  'file_state' as "table",
  "isFileOwner"::boolean as "0",
  "isPinned"::boolean as "1",
  null::boolean as "2",
  null::boolean as "3",
  null::boolean as "4",
  null::boolean as "5",
  null::boolean as "6",
  null::boolean as "7",
  null::boolean as "8",
  "firstVisitAt"::bigint as "9",
  "lastEditAt"::bigint as "10",
  "lastVisitAt"::bigint as "11",
  null::bigint as "12",
  "fileId"::text as "13",
  "lastSessionState"::text as "14",
  "userId"::text as "15",
  null::text as "16",
  null::text as "17",
  null::text as "18",
  null::text as "19",
  null::text as "20",
  null::text as "21",
  null::text as "22",
  null::text as "23"
FROM my_file_states
UNION ALL
SELECT
  'file' as "table",
  "isDeleted"::boolean as "0",
  "isEmpty"::boolean as "1",
  "published"::boolean as "2",
  "shared"::boolean as "3",
  null::boolean as "4",
  null::boolean as "5",
  null::boolean as "6",
  null::boolean as "7",
  null::boolean as "8",
  "createdAt"::bigint as "9",
  "lastPublished"::bigint as "10",
  "updatedAt"::bigint as "11",
  null::bigint as "12",
  "createSource"::text as "13",
  "id"::text as "14",
  "name"::text as "15",
  "ownerAvatar"::text as "16",
  "ownerId"::text as "17",
  "ownerName"::text as "18",
  "publishedSlug"::text as "19",
  "sharedLinkType"::text as "20",
  "thumbnail"::text as "21",
  null::text as "22",
  null::text as "23"
FROM all_files
UNION ALL
SELECT
  'user_mutation_number' as "table",
  null::boolean as "0",
  null::boolean as "1",
  null::boolean as "2",
  null::boolean as "3",
  null::boolean as "4",
  null::boolean as "5",
  null::boolean as "6",
  null::boolean as "7",
  null::boolean as "8",
  "mutationNumber"::bigint as "9",
  null::bigint as "10",
  null::bigint as "11",
  null::bigint as "12",
  null::text as "13",
  null::text as "14",
  null::text as "15",
  null::text as "16",
  null::text as "17",
  null::text as "18",
  null::text as "19",
  null::text as "20",
  null::text as "21",
  null::text as "22",
  null::text as "23"
FROM public."user_mutation_number"
WHERE "userId" = $1
UNION ALL
SELECT
  'lsn' as "table",
  null::boolean as "0",
  null::boolean as "1",
  null::boolean as "2",
  null::boolean as "3",
  null::boolean as "4",
  null::boolean as "5",
  null::boolean as "6",
  null::boolean as "7",
  null::boolean as "8",
  null::bigint as "9",
  null::bigint as "10",
  null::bigint as "11",
  null::bigint as "12",
  pg_current_wal_lsn()::text as "13",
  null::text as "14",
  null::text as "15",
  null::text as "16",
  null::text as "17",
  null::text as "18",
  null::text as "19",
  null::text as "20",
  null::text as "21",
  null::text as "22",
  null::text as "23"
`

export const columnNamesByAlias = {
	user: {
		'0': 'allowAnalyticsCookie',
		'1': 'areKeyboardShortcutsEnabled',
		'2': 'enhancedA11yMode',
		'3': 'exportBackground',
		'4': 'exportPadding',
		'5': 'isDynamicSizeMode',
		'6': 'isPasteAtCursorMode',
		'7': 'isSnapMode',
		'8': 'isWrapMode',
		'9': 'animationSpeed',
		'10': 'createdAt',
		'11': 'edgeScrollSpeed',
		'12': 'updatedAt',
		'13': 'avatar',
		'14': 'color',
		'15': 'colorScheme',
		'16': 'email',
		'17': 'exportFormat',
		'18': 'exportTheme',
		'19': 'flags',
		'20': 'id',
		'21': 'inputMode',
		'22': 'locale',
		'23': 'name',
	},
	file_state: {
		'0': 'isFileOwner',
		'1': 'isPinned',
		'9': 'firstVisitAt',
		'10': 'lastEditAt',
		'11': 'lastVisitAt',
		'13': 'fileId',
		'14': 'lastSessionState',
		'15': 'userId',
	},
	file: {
		'0': 'isDeleted',
		'1': 'isEmpty',
		'2': 'published',
		'3': 'shared',
		'9': 'createdAt',
		'10': 'lastPublished',
		'11': 'updatedAt',
		'13': 'createSource',
		'14': 'id',
		'15': 'name',
		'16': 'ownerAvatar',
		'17': 'ownerId',
		'18': 'ownerName',
		'19': 'publishedSlug',
		'20': 'sharedLinkType',
		'21': 'thumbnail',
	},
	user_mutation_number: {
		'9': 'mutationNumber',
	},
	lsn: {
		'13': 'lsn',
	},
}
