name: Setup tldraw/tldraw
description: Set up node & yarn

runs:
  using: composite
  steps:
    # see https://github.com/actions/setup-node/issues/899 for one of the reasons why this
    # needs to be done before action/setup-node
    - name: Enable corepack
      run: npm i -g corepack
      shell: bash

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: 22.16.0
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
