/* eslint-disable no-console */
/**
 * Extract the input points from src/corpus/raw.json (a tldraw snapshot of real hand-drawn
 * strokes) into src/corpus/real.ts so the corpus can use them without depending on tlschema.
 *
 *   yarn workspace @tldraw/freehand extract-raw
 *
 * Draw shape segments store their points as delta-encoded base64 (see tlschema's b64Vecs):
 * the first point is 3 little-endian Float32s, each subsequent point is 3 little-endian
 * Float16 deltas from the previous point. This script decodes that back to absolute points.
 */
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const here = dirname(fileURLToPath(import.meta.url))
const corpusDir = join(here, '..', 'src', 'corpus')

function float16BitsToNumber(bits: number): number {
	const sign = bits >> 15 ? -1 : 1
	const exp = (bits >> 10) & 0x1f
	const frac = bits & 0x3ff
	if (exp === 0) return sign * frac * 2 ** -24
	if (exp === 31) return frac ? NaN : sign * Infinity
	return sign * 2 ** (exp - 15) * (1 + frac / 1024)
}

interface Point {
	x: number
	y: number
	z: number
}

function decodePoints(base64: string): Point[] {
	if (base64.length === 0) return []
	const bytes = Buffer.from(base64, 'base64')
	const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)

	// First point is 3 Float32s (12 bytes)
	let x = view.getFloat32(0, true)
	let y = view.getFloat32(4, true)
	let z = view.getFloat32(8, true)
	const result: Point[] = [{ x, y, z }]

	// Subsequent points are 3 Float16 deltas (6 bytes each)
	for (let offset = 12; offset < bytes.length; offset += 6) {
		x += float16BitsToNumber(view.getUint16(offset, true))
		y += float16BitsToNumber(view.getUint16(offset + 2, true))
		z += float16BitsToNumber(view.getUint16(offset + 4, true))
		result.push({ x, y, z })
	}
	return result
}

interface RawDrawShape {
	id: string
	type: string
	props: {
		segments: { type: string; path: string }[]
		size: string
		dash: string
		isPen: boolean
		isComplete: boolean
	}
}

const raw = JSON.parse(readFileSync(join(corpusDir, 'raw.json'), 'utf-8')) as {
	shapes: RawDrawShape[]
}

const strokes = raw.shapes
	.filter((s) => s.type === 'draw')
	.map((shape) => {
		// The corpus presets assume mouse-drawn 'draw' strokes; anything else in a future
		// raw.json needs its own options wired up in strokes.ts.
		const { size, dash, isPen, isComplete } = shape.props
		if (size !== 'xl' || dash !== 'draw' || isPen || !isComplete) {
			throw new Error(`unexpected props on ${shape.id}: ${JSON.stringify(shape.props)}`)
		}
		const points = shape.props.segments.flatMap((segment) => decodePoints(segment.path))
		return { id: shape.id.replace('shape:', ''), points }
	})

const entries = strokes
	.map(({ id, points }) => {
		const flat = points.flatMap((p) => [p.x, p.y, p.z])
		return `\t{ id: '${id}', points: pts(${JSON.stringify(flat)}) },`
	})
	.join('\n')

const output = `// Generated by scripts/extract-raw.ts from raw.json. Do not edit by hand.
/* eslint-disable no-loss-of-precision -- the literals round-trip exactly; the rule false-positives on long decimals */
import { VecModel } from '../vendor'

function pts(flat: number[]): VecModel[] {
	const points: VecModel[] = []
	for (let i = 0; i < flat.length; i += 3) {
		points.push({ x: flat[i], y: flat[i + 1], z: flat[i + 2] })
	}
	return points
}

/** Real hand-drawn strokes recorded in tldraw, decoded from raw.json. */
export const REAL_STROKES: { id: string; points: VecModel[] }[] = [
${entries}
]
`

writeFileSync(join(corpusDir, 'real.ts'), output)
console.log(
	`wrote real.ts: ${strokes.length} strokes, ${strokes.reduce((n, s) => n + s.points.length, 0)} points`
)
