FROM rocicorp/zero:__ZERO_VERSION as zero

FROM nginx:alpine

# Copy everything from the rocicorp/zero image
COPY --from=zero / /

# Install supervisor for process management and gettext for envsubst
RUN apk add --no-cache supervisor gettext

# Copy our configs
COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY supervisord.conf /etc/supervisord.conf
COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 4848

CMD ["/start.sh"]
