import { Box, Editor, FileHelpers, structuredClone } from 'tldraw'
import { TldrawAiTransformConstructor } from './TldrawAiTransform'
import { TLAiContent, TLAiMessages, TLAiPrompt, TLAiStreamingChange } from './types'
import { TldrawAiApplyFn } from './useTldrawAi'
import { asMessage } from './utils'

/** @public */
export interface TldrawAiModuleOptions {
	editor: Editor
	transforms?: TldrawAiTransformConstructor[]
}

/**
 * The AI manager for tldraw. This class is used to produce prompts for the AI
 * using data from the editor, and to update the editor based on the
 * changes generated by the AI.
 *
 * @public
 */
export class TldrawAiModule {
	constructor(public readonly opts = {} as TldrawAiModuleOptions) {}

	dispose() {}

	/**
	 * Creates and prepare a prompt, returning the prompt
	 * and a function to handle changes.
	 *
	 * @param prompt - The user's message or a configuration for the prompt
	 */
	async generate(prompt: string | { message: TLAiMessages; stream?: boolean }) {
		const { transforms: _transformCtors = [] } = this.opts
		const transforms = _transformCtors.map((ctor) => new ctor(this.opts.editor))

		const message = typeof prompt === 'string' ? prompt : prompt.message
		let _prompt = await this.getPrompt(message)

		for (const transform of transforms) {
			if (transform.transformPrompt) {
				_prompt = transform.transformPrompt(_prompt)
			}
		}

		transforms.reverse()

		const handleChange = (change: TLAiStreamingChange, apply: TldrawAiApplyFn) => {
			for (const transform of transforms) {
				if (transform.transformChange) {
					change = transform.transformChange(change)
				}
			}
			apply({ change, editor: this.opts.editor })
		}

		return {
			prompt: _prompt,
			handleChange,
		}
	}

	/**
	 * Create the prompt to be sent to the AI.
	 *
	 * @param prompt - The user's prompt
	 * @param options - Options to generate the input
	 */
	async getPrompt(
		prompt: TLAiMessages,
		options = {} as Partial<Pick<TLAiPrompt, 'canvasContent' | 'contextBounds' | 'promptBounds'>>
	): Promise<TLAiPrompt> {
		const { editor } = this.opts
		const {
			contextBounds = editor.getViewportPageBounds(),
			promptBounds = editor.getViewportPageBounds(),
		} = options

		const content = options.canvasContent ?? this.getContent(promptBounds)

		// Get image from the content
		const image = await this.getImage(content)

		return {
			message: asMessage(prompt),
			canvasContent: content,
			contextBounds: roundBox(contextBounds),
			promptBounds: roundBox(promptBounds),
			image,
		}
	}

	/**
	 * Get the content from the current page.
	 *
	 * @param bounds - The bounds to get the content for
	 */
	private getContent(bounds: Box): TLAiContent {
		const { editor } = this.opts

		// Get the page content (same as what we put on the clipboard when a user copies) for the shapes
		// that are included (contained or colliding with) the provided bounds

		let content: TLAiContent | undefined = {
			bindings: [],
			shapes: [],
			assets: [],
			...editor.getContentFromCurrentPage(
				editor
					.getCurrentPageShapesSorted()
					.filter((s) => bounds.includes(editor.getShapeMaskedPageBounds(s)!))
			),
		}

		// If we don't have content, it's either an empty page or an empty section of the page.
		// This is an acceptable case; but let's send along an empty content instead of undefined.
		if (content) {
			// the content is a TLContent, but we want to omit the schema for TLAiContent
			content.shapes = structuredClone(content.shapes)
			content.bindings = structuredClone(content.bindings)
			delete (content as any).schema
			delete (content as any).rootShapeIds
		} else {
			content = {
				shapes: [],
				bindings: [],
				assets: [],
			}
		}

		return content
	}

	/**
	 * Get a screenshot (data URL) of the prompt's content
	 *
	 * @param content - The content to get the image from
	 */
	private async getImage(content: TLAiContent) {
		if (!content.shapes.length) return undefined

		const result = await this.opts.editor.toImage(content.shapes, {
			format: 'jpeg',
			background: false,
			darkMode: false,
			padding: 0, // will the context bounds take into account the padding?
		})

		return await FileHelpers.blobToDataUrl(result.blob)
	}
}

function roundBox(box: Box) {
	const b = box.clone()
	b.x = Math.round(b.x)
	b.y = Math.round(b.y)
	b.width = Math.round(b.width)
	b.height = Math.round(b.height)
	return b
}
