// This file is automatically generated by refresh-create-templates.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export interface Template {
	repo: string
	name: string
	description: string
	shortDescription?: string
	order?: number
}

export const TEMPLATES: Template[] = [
	{
		name: 'Basic',
		description: 'A minimal tldraw template with Vite, React, and TypeScript.',
		order: 1,
		repo: 'tldraw/vite-template',
	},
	{
		name: 'Shader Starter Kit',
		description:
			'A tldraw template with WebGL shader starter kit that creates dynamic shader effects from shape geometry.',
		order: 10,
		repo: 'tldraw/shader-starter-kit',
	},
	{
		name: 'Agent',
		description: 'Enable AI agents to interpret and interact with canvas drawings and elements.',
		shortDescription: 'An AI-powered agent.',
		repo: 'tldraw/agent-template',
	},
	{
		name: 'Branching chat',
		description:
			'Create interactive chat trees using visual branching conversation interface with AI integration.',
		shortDescription: 'A branching chat interface.',
		repo: 'tldraw/branching-chat-template',
	},
	{
		name: 'Chat',
		description:
			'Use tldraw to add sketches and annotated images as visual context in an LLM chat interface.',
		shortDescription: 'A chat UI with sketches and images as context for AI.',
		repo: 'tldraw/chat-template',
	},
	{
		name: 'Multiplayer',
		description:
			'Bring multiplayer mode to your tldraw canvas app. Self-hosted and powered by tldraw sync and Cloudflare Durable Objects.',
		shortDescription: 'Real-time multiplayer for tldraw, built with Cloudflare Durable Objects.',
		repo: 'tldraw/tldraw-sync-cloudflare',
	},
	{
		name: 'Workflow',
		description:
			'Build visual tools where users drag and connect nodes, think automation builders with a canvas interface.',
		shortDescription: 'Visual node-based builder for workflows.',
		repo: 'tldraw/workflow-template',
	},
]
