// This file is automatically generated by refresh-create-templates.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export interface Template {
	repo: string
	name: string
	description: string
	shortDescription?: string
	order?: number
}

export const TEMPLATES: Template[] = [
	{
		name: 'Basic',
		description: 'A minimal tldraw template with Vite, React, and TypeScript.',
		order: 1,
		repo: 'tldraw/vite-template',
	},
	{
		name: 'Multiplayer',
		description:
			'Real-time multiplayer with a self-hosted backend powered by tldraw sync and Cloudflare Durable Objects.',
		shortDescription: 'Real-time multiplayer.',
		order: 2,
		repo: 'tldraw/tldraw-sync-cloudflare',
	},
	{
		name: 'Agent',
		description: 'Work on the canvas with an AI agent.',
		shortDescription: 'An AI-powered agent.',
		order: 3,
		repo: 'tldraw/agent-template',
	},
	{
		name: 'Workflow',
		description:
			'Build visual tools where users drag and connect nodes, think automation builders with a canvas interface.',
		shortDescription: 'Visual node-based builder for workflows.',
		order: 4,
		repo: 'tldraw/workflow-template',
	},
	{
		name: 'Chat',
		description:
			'Use tldraw to add sketches and annotated images as visual context in an LLM chat interface.',
		shortDescription: 'A chat UI with sketches and images as context for AI.',
		order: 5,
		repo: 'tldraw/chat-template',
	},
	{
		name: 'Branching chat',
		description: 'Chat with an AI using a branching conversation interface.',
		shortDescription: 'A branching chat interface.',
		order: 6,
		repo: 'tldraw/branching-chat-template',
	},
	{
		name: 'Shader',
		description: 'Use WebGL shaders that use shape geometry to create dynamic effects.',
		shortDescription: 'Shaders on the canvas.',
		order: 7,
		repo: 'tldraw/shader-starter-kit',
	},
]
