// This file is automatically generated by refresh-create-templates.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export interface Template {
	repo: string
	name: string
	description: string
	category: 'framework' | 'app'
	order?: number
}

export interface Templates {
	framework: Template[]
	app: Template[]
}

export const TEMPLATES: Templates = {
	app: [
		{
			repo: 'tldraw/tldraw-sync-cloudflare',
			name: 'Multiplayer sync',
			description:
				'Self-hosted tldraw with realtime multiplayer, powered by tldraw sync and Cloudflare Durable Objects. Built with Vite and TypeScript.',
			category: 'app',
			order: 1,
		},
		{
			repo: 'tldraw/ai-template',
			name: 'AI starter kit',
			description:
				'tldraw + the @tldraw/ai module, built with Vite and TypeScript. This app includes a Cloudflare Worker that connects to the OpenAI API.',
			category: 'app',
		},
		{
			repo: 'tldraw/branching-chat',
			name: 'Branching chat starter kit',
			description: 'A branching chat application using tldraw and OpenAI.',
			category: 'app',
		},
	],
	framework: [
		{
			repo: 'tldraw/vite-template',
			name: 'Vite + tldraw',
			description:
				'The easiest way to get started with tldraw. Built with Vite, React, and TypeScript.',
			category: 'framework',
			order: 1,
		},
		{
			repo: 'tldraw/nextjs-template',
			name: 'Next.js + tldraw',
			description: 'tldraw in a Next.js app, with TypeScript.',
			category: 'framework',
			order: 2,
		},
		{
			repo: 'tldraw/vue-template',
			name: 'Vue.js + tldraw',
			description: 'tldraw in a Vue.js app, built with Vite and TypeScript.',
			category: 'framework',
		},
	],
}
