// This file is automatically generated by internal/scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export const version = '4.3.2'
export const publishDates = {
	major: '2025-09-18T14:39:22.803Z',
	minor: '2026-01-21T12:02:39.450Z',
	patch: '2026-02-14T22:18:29.448Z',
}
