// This file is automatically generated by internal/scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export const version = '4.0.2'
export const publishDates = {
	major: '2025-09-18T14:32:28.865Z',
	minor: '2025-09-18T14:32:28.865Z',
	patch: '2025-09-19T11:04:14.309Z',
}
