{
 "title": "Events",
 "tags": [
  "provisioned",
  "repo:tldraw/tldraw"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment: production | staging | pr-42",
    "query": "production"
   }
  ]
 },
 "panels": [
  {
   "title": "Room events",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formatAs": "time_series",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, count() as total\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n\tGROUP BY date, event\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND event != 'replicator'\n\tAND event != 'user_durable_object'\n\tGROUP BY date, event\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '120' SECOND) as date, blob1 as event, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1733213050) AND timestamp <= toDateTime(1733385850)\n\tAND blob2 = 'pr-5028-tldraw-multiplayer'\n\tAND event != 'replicator'\n\tAND event != 'user_durable_object'\n\tGROUP BY date, event\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Replicator requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT \n    toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date,\n    blob3 as name,\n    max(double1) as total\nFROM 'MEASURE'\nWHERE \n    timestamp >= toDateTime($from) \n    AND timestamp <= toDateTime($to)\n    AND blob1 = 'replicator'\n    AND blob2 = '${environment}-tldraw-multiplayer'\n    AND blob3 = 'rpm'\nGROUP BY date, name\nORDER BY date ASC",
     "rawQuery": "SELECT \n    toStartOfInterval(timestamp, INTERVAL '120' SECOND) as date,\n    blob3 as name,\n    max(double1) as total\nFROM 'MEASURE'\nWHERE \n    timestamp >= toDateTime(1733133735) \n    AND timestamp <= toDateTime(1733392935)\n    AND blob1 = 'replicator'\n    AND blob2 = 'pr-5028-tldraw-multiplayer'\n    AND blob3 = 'rpm'\nGROUP BY date, name\nORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Replicator boot duration",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as env, blob3 as name, avg(double1) as avg_boot_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n\tAND env = '${environment}-tldraw-multiplayer'\n    AND event = 'replicator'\n\tAND name = 'reboot_duration'\n\tGROUP BY env, date, event, name\n\tORDER BY date DESC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '60' SECOND) as date, blob1 as event, blob2 as env, blob3 as name, avg(double1) as avg_boot_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1733217590) AND timestamp <= toDateTime(1733390390)\n\tAND env = 'pr-5028-tldraw-multiplayer'\n    AND event = 'replicator'\n\tAND name = 'reboot_duration'\n\tGROUP BY env, date, event, name\n\tORDER BY date DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Replicator events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob3 as name, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND blob1 = 'replicator'\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND name != 'active_users'\n\tAND name != 'rpm'\n\tAND name != 'reboot_duration'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '20' SECOND) as date, blob3 as name, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1739393132) AND timestamp <= toDateTime(1739436332)\n    AND blob1 = 'replicator'\n\tAND blob2 = 'pr-5416-tldraw-multiplayer'\n\tAND name != 'active_users'\n\tAND name != 'rpm'\n\tAND name != 'reboot_duration'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Replicator reboots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob3 as name, blob4 as source, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND blob1 = 'replicator'\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND name = 'reboot'\n\tGROUP BY date, name, source\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '20' SECOND) as date, blob3 as name, blob4 as source, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1739393303) AND timestamp <= toDateTime(1739436503)\n    AND blob1 = 'replicator'\n\tAND blob2 = 'pr-5416-tldraw-multiplayer'\n\tAND name = 'reboot'\n\tGROUP BY date, name, source\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Replicator registered users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob3 as name, max(double1) \n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND blob1 = 'replicator'\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND name = 'active_users'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '300' SECOND) as date, blob3 as name, max(double1) \n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1738754410) AND timestamp <= toDateTime(1739359210)\n    AND blob1 = 'replicator'\n\tAND blob2 = 'production-tldraw-multiplayer'\n\tAND name = 'active_users'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "User DO  + UserDataSyncer events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob3 as name, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n\tAND blob1 = 'user_durable_object'\n\tAND blob2 = '${environment}-tldraw-multiplayer'   \n\tAND name != 'reboot_duration'\n\tAND name != 'cold_start_time'\n\tGROUP BY  date, name\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '20' SECOND) as date, blob3 as name, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1738886334) AND timestamp <= toDateTime(1738929534)\n\tAND blob1 = 'user_durable_object'\n\tAND blob2 = 'pr-5380-tldraw-multiplayer'   \n\tAND name != 'reboot_duration'\n\tAND name != 'cold_start_time'\n\tGROUP BY  date, name\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Average UserDataSyncer boot duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formatAs": "time_series",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob3 as name, avg(double1) as avg_boot_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND blob1 = 'user_durable_object'\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND name = 'reboot_duration'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '300' SECOND) as date, blob3 as name, avg(double1) as avg_boot_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1738906685) AND timestamp <= toDateTime(1738928285)\n    AND blob1 = 'user_durable_object'\n\tAND blob2 = 'production-tldraw-multiplayer'\n\tAND name = 'reboot_duration'\n\tGROUP BY date, name\n\tORDER BY date ASC"
    }
   ]
  },
  {
   "title": "Maximum UserDataSyncer boot duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' MINUTE) as date, max(double1) as max_boot_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND blob1 = 'user_durable_object'\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND blob3 = 'reboot_duration'\n\tGROUP BY date",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '300' MINUTE) as date, max(double1) as max_boot_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1738885901) AND timestamp <= toDateTime(1738929101)\n    AND blob1 = 'user_durable_object'\n\tAND blob2 = 'pr-5380-tldraw-multiplayer'\n\tAND blob3 = 'reboot_duration'\n\tGROUP BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Average UserDataSyncer cold start duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formatAs": "time_series",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob3 as name, avg(double1) as avg_cold_start_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND blob1 = 'user_durable_object'\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND name = 'cold_start_time'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '20' SECOND) as date, blob3 as name, avg(double1) as avg_cold_start_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1738885737) AND timestamp <= toDateTime(1738928937)\n    AND blob1 = 'user_durable_object'\n\tAND blob2 = 'pr-5380-tldraw-multiplayer'\n\tAND name = 'cold_start_time'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "UserDataSyncer boot count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob3 as name, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND blob1 = 'user_durable_object'\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND name = 'reboot'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '120' SECOND) as date, blob3 as name, count() as total\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1733217590) AND timestamp <= toDateTime(1733390390)\n    AND blob1 = 'user_durable_object'\n\tAND blob2 = 'pr-5028-tldraw-multiplayer'\n\tAND name = 'reboot'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "pierre incremental total bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formatAs": "time_series",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as name, sum(double1) as avg_cold_start_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n\tAND blob2 = '${environment}-tldraw-multiplayer'\n\tAND name = 'pierre_incremental_write_chars'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '86400' SECOND) as date, blob1 as name, sum(double1) as avg_cold_start_duration\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1776072130) AND timestamp <= toDateTime(1776676930)\n\tAND blob2 = 'production-tldraw-multiplayer'\n\tAND name = 'pierre_incremental_write_chars'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "max attempts before persistence success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formatAs": "time_series",
     "formattedQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as event, blob2 as type, blob3 as rpm\n\tFROM 'MEASURE'\n    WHERE NOT endsWith(event, 'tldraw-multiplayer')\n\tAND timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND event = 'replicator'\n\tGROUP BY date, event, type, blob3\n\tORDER BY date ASC",
     "query": "SELECT toStartOfInterval(timestamp, INTERVAL '$interval' SECOND) as date, blob1 as name, max(double1) as avg_attempts\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime($from) AND timestamp <= toDateTime($to)\n    AND name = 'persist_success'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "rawQuery": "SELECT toStartOfInterval(timestamp, INTERVAL '300' SECOND) as date, blob1 as name, max(double1) as avg_attempts\n\tFROM 'MEASURE'\n\tWHERE timestamp >= toDateTime(1762169567) AND timestamp <= toDateTime(1762180367)\n    AND name = 'persist_success'\n\tGROUP BY date, name\n\tORDER BY date ASC",
     "round": "0s"
    }
   ]
  }
 ]
}