name: Bug report
description: File a bug report
type: Bug
title: ''
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen instead.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce the bug?
      description: |
        Please share the steps to reproduce this bug. A [StackBlitz reproduction](https://stackblitz.com/edit/vitejs-vite-ahoswhus?file=src%2FApp.tsx) or screen recording helps us fix it faster.
    validations:
      required: false
  - type: dropdown
    id: browsers
    validations:
      required: false
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: product
    attributes:
      label: Where did this happen?
      options:
        - tldraw SDK (@tldraw/tldraw npm package)
        - tldraw.com
        - tldraw.dev (documentation site)
        - VS Code extension
        - Obsidian plugin
    validations:
      required: true
