name: Example request
description: Submit a request for an example
type: Example
title: ''
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Need an example of how to do something with tldraw? We're happy to help!
  - type: textarea
    id: description
    attributes:
      label: What's the example?
      description: Describe what you're trying to build or the use case you'd like to see demonstrated.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/tldraw/tldraw/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
