name: Feature request
description: Suggest a new feature or improvement
title: ''
labels: ['feature']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a feature or improvement in tldraw? We'd love to hear it!
  - type: textarea
    id: description
    attributes:
      label: What's the feature?
      description: Describe the feature, the problem it solves, and any examples from other apps.
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: Where would you like this feature?
      options:
        - tldraw SDK (@tldraw/tldraw npm package)
        - tldraw.com
        - makereal.tldraw.com
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/tldraw/tldraw/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
