name: Task
description: Create a task
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the task.
    validations:
      required: true
