// Generated by `yarn gen-controls` from component Props types. Do not edit.
// Regenerate when a sketchbook component's props change.
import { ArgType } from './sketch'

export const autoArgTypes: Record<string, Record<string, ArgType>> = {
	'sketchbooks/button.sketchbook.tsx': {
		label: {
			control: 'text',
		},
		tone: {
			control: 'select',
			options: ['default', 'primary'],
		},
	},
	'sketchbooks/editor-probe.sketchbook.tsx': {
		label: {
			control: 'text',
		},
	},
	'sketchbooks/tldraw-button.sketchbook.tsx': {
		action: {
			control: 'text',
		},
		type: {
			control: 'select',
			options: ['danger', 'low', 'normal', 'primary'],
		},
	},
}
