// Generated by `yarn gen-controls` from component Props types. Do not edit.
// Regenerate when a sketchbook component's props change.
import { ArgType } from './sketch'

export const autoArgTypes: Record<string, Record<string, ArgType>> = {
	'sketchbooks/button.sketchbook.tsx': {
		label: {
			control: 'text',
		},
		tone: {
			control: 'select',
			options: ['default', 'primary'],
		},
	},
	'sketchbooks/comments/comment-card.sketchbook.tsx': {
		author: {
			control: 'text',
		},
		body: {
			control: 'text',
		},
		time: {
			control: 'text',
		},
		you: {
			control: 'boolean',
		},
	},
	'sketchbooks/comments/comment-composer.sketchbook.tsx': {
		author: {
			control: 'text',
		},
		placeholder: {
			control: 'text',
		},
	},
	'sketchbooks/comments/comment-pin.sketchbook.tsx': {
		number: {
			control: 'number',
		},
		resolved: {
			control: 'boolean',
		},
	},
	'sketchbooks/comments/comment-thread.sketchbook.tsx': {
		resolved: {
			control: 'boolean',
		},
	},
	'sketchbooks/editor-probe.sketchbook.tsx': {
		label: {
			control: 'text',
		},
	},
	'sketchbooks/tldraw-button.sketchbook.tsx': {
		action: {
			control: 'text',
		},
		type: {
			control: 'select',
			options: ['danger', 'low', 'normal', 'primary'],
		},
	},
}
