// Build the freehand WASM crate and inline it (base64) into a generated TS module so it is
// importable from the editor package in both Node and the browser with no bundler/asset
// configuration. Run: node freehand-wasm/build.mjs  (from packages/editor)
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkg = resolve(here, '..')

console.log('Building freehand-wasm (release, wasm32-unknown-unknown)...')
execSync('cargo build --release --target wasm32-unknown-unknown', { cwd: here, stdio: 'inherit' })

const wasmPath = resolve(here, 'target/wasm32-unknown-unknown/release/freehand_wasm.wasm')
const bytes = readFileSync(wasmPath)
const b64 = bytes.toString('base64')

const out = resolve(pkg, 'src/lib/utils/freehand-wasm/freehand-wasm.generated.ts')
writeFileSync(
	out,
	`// Generated by freehand-wasm/build.mjs — do not edit by hand.\n` +
		`// Source: packages/editor/freehand-wasm/src/lib.rs\n` +
		`// Size: ${bytes.length} bytes (base64 below).\n` +
		`/* eslint-disable */\n` +
		`export const freehandWasmBase64 =\n\t'${b64}'\n`
)
console.log(`Wrote ${out} (${bytes.length} bytes wasm, ${b64.length} bytes base64)`)
