// This file is automatically generated by internal/scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export const version = '3.13.2'
export const publishDates = {
	major: '2024-09-13T14:36:29.063Z',
	minor: '2025-05-22T13:38:59.946Z',
	patch: '2025-06-24T11:29:07.723Z',
}
