// This file is automatically generated by internal/scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export const version = '4.2.1'
export const publishDates = {
	major: '2025-09-18T14:39:22.803Z',
	minor: '2025-11-19T11:53:58.692Z',
	patch: '2025-12-05T12:36:16.200Z',
}
