export const CONNECTION_CENTER_HANDLE_SIZE_PX = 16
export const CONNECTION_CENTER_HANDLE_HOVER_SIZE_PX = 24

export const NODE_WIDTH_PX = 400
export const NODE_HEIGHT_PX = 54

export const PORT_RADIUS_PX = 6

export const DEFAULT_NODE_SPACING_PX = 60
