// Google regional domains
// https://www.google.com/supported_domains
const googleRegionalDomains = [
	'ad',
	'ae',
	'al',
	'am',
	'as',
	'at',
	'az',
	'ba',
	'be',
	'bf',
	'bg',
	'bi',
	'bj',
	'bs',
	'bt',
	'by',
	'ca',
	'cat',
	'cd',
	'cf',
	'cg',
	'ch',
	'ci',
	'cl',
	'cm',
	'cn',
	'co.ao',
	'co.bw',
	'co.ck',
	'co.cr',
	'co.id',
	'co.il',
	'co.in',
	'co.jp',
	'co.ke',
	'co.kr',
	'co.ls',
	'co.ma',
	'co.mz',
	'co.nz',
	'co.th',
	'co.tz',
	'co.ug',
	'co.uk',
	'co.uz',
	'co.ve',
	'co.vi',
	'co.za',
	'co.zm',
	'co.zw',
	'com',
	'com.af',
	'com.ag',
	'com.ar',
	'com.au',
	'com.bd',
	'com.bh',
	'com.bn',
	'com.bo',
	'com.br',
	'com.bz',
	'com.co',
	'com.cu',
	'com.cy',
	'com.do',
	'com.ec',
	'com.eg',
	'com.et',
	'com.fj',
	'com.gh',
	'com.gi',
	'com.gt',
	'com.hk',
	'com.jm',
	'com.kh',
	'com.kw',
	'com.lb',
	'com.ly',
	'com.mm',
	'com.mt',
	'com.mx',
	'com.my',
	'com.na',
	'com.ng',
	'com.ni',
	'com.np',
	'com.om',
	'com.pa',
	'com.pe',
	'com.pg',
	'com.ph',
	'com.pk',
	'com.pr',
	'com.py',
	'com.qa',
	'com.sa',
	'com.sb',
	'com.sg',
	'com.sl',
	'com.sv',
	'com.tj',
	'com.tr',
	'com.tw',
	'com.ua',
	'com.uy',
	'com.vc',
	'com.vn',
	'cv',
	'cz',
	'de',
	'dj',
	'dk',
	'dm',
	'dz',
	'ee',
	'es',
	'fi',
	'fm',
	'fr',
	'ga',
	'ge',
	'gg',
	'gl',
	'gm',
	'gr',
	'gy',
	'hn',
	'hr',
	'ht',
	'hu',
	'ie',
	'im',
	'iq',
	'is',
	'it',
	'je',
	'jo',
	'kg',
	'ki',
	'kz',
	'la',
	'li',
	'lk',
	'lt',
	'lu',
	'lv',
	'md',
	'me',
	'mg',
	'mk',
	'ml',
	'mn',
	'mu',
	'mv',
	'mw',
	'ne',
	'nl',
	'no',
	'nr',
	'nu',
	'pl',
	'pn',
	'ps',
	'pt',
	'ro',
	'rs',
	'ru',
	'rw',
	'sc',
	'se',
	'sh',
	'si',
	'sk',
	'sm',
	'sn',
	'so',
	'sr',
	'st',
	'td',
	'tg',
	'tl',
	'tm',
	'tn',
	'to',
	'tt',
	'vu',
	'ws',
].map((tld) => `https://www.google.${tld}`)

export const cspDirectives: { [key: string]: string[] } = {
	'default-src': [`'self'`],
	'connect-src': [
		`'self'`,
		`ws:`,
		`wss:`,
		'blob:',
		'data:',
		'http://localhost:8788',
		`https://*.tldraw.xyz`,
		`https://cdn.tldraw.com`,
		`https://*.tldraw.workers.dev`,
		`https://*.ingest.sentry.io`,
		`https://*.ingest.us.sentry.io`,
		'https://*.analytics.google.com',
		'https://www.google-analytics.com',
		'https://*.googletagmanager.com',
		'https://www.googletagmanager.com',
		...googleRegionalDomains,
		// for thumbnail server
		'http://localhost:5002',
		'https://*.clerk.accounts.dev',
		'https://clerk.tldraw.com',
		'https://clerk.staging.tldraw.com',
		// zero
		'https://*.zero.tldraw.com',
		'https://zero.tldraw.com',
		'http://localhost:4848',
		'https://analytics.tldraw.com',
		'https://stats.g.doubleclick.net',
		'https://*.google-analytics.com',
		'https://api.reo.dev',
		'https://fonts.googleapis.com',
	],
	'font-src': [`'self'`, `https://fonts.googleapis.com`, `https://fonts.gstatic.com`, 'data:'],
	'frame-src': [`'self'`, `https:`],
	'img-src': [`'self'`, `http:`, `https:`, `data:`, `blob:`],
	'media-src': [`'self'`, `http:`, `https:`, `data:`, `blob:`],
	'script-src': [
		`'self'`,
		'https://challenges.cloudflare.com',
		'https://*.clerk.accounts.dev',
		'https://clerk.tldraw.com',
		'https://clerk.staging.tldraw.com',
		// embeds that have scripts
		'https://gist.github.com',
		'https://www.googletagmanager.com',
		'https://*.googletagmanager.com',
		'https://www.google-analytics.com',
		'https://*.google-analytics.com',
		'https://analytics.tldraw.com',
		'https://static.reo.dev',
	],
	'worker-src': [`'self'`, `blob:`],
	'style-src': [`'self'`, `'unsafe-inline'`, `https://fonts.googleapis.com`],
	'style-src-elem': [
		`'self'`,
		`'unsafe-inline'`,
		`https://fonts.googleapis.com`,
		// embeds that have styles
		'https://github.githubassets.com',
	],
	'report-uri': [process.env.SENTRY_CSP_REPORT_URI ?? ``],
}

export const csp = Object.keys(cspDirectives)
	.map((directive) => `${directive} ${cspDirectives[directive].join(' ')}`)
	.join('; ')

export const cspDev = Object.keys(cspDirectives)
	.filter((key) => key !== 'report-uri')
	.map((directive) => `${directive} ${cspDirectives[directive].join(' ')}`)
	.join('; ')
