// This file is automatically generated by scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

/** @public */
export type TLCanonicalStickerType =
	| 'blue-circle'
	| 'heart'
	| 'question-mark'
	| 'star'
	| 'thumbs-down'
	| 'thumbs-up'

/** @public */
export const stickerTypes = [
	'blue-circle',
	'heart',
	'question-mark',
	'star',
	'thumbs-down',
	'thumbs-up',
] as const
