// This file is automatically generated by internal/scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export const version = '3.10.0'
export const publishDates = {
	major: '2024-09-13T14:36:29.063Z',
	minor: '2025-03-11T14:20:29.409Z',
	patch: '2025-03-11T14:20:29.409Z',
}
