// This file is automatically generated by scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export const version = '2.3.0'
export const publishDates = {
	major: '2024-06-28T10:56:07.893Z',
	minor: '2024-07-02T16:49:50.397Z',
	patch: '2024-07-02T16:49:50.397Z',
}
