// This file is automatically generated by internal/scripts/refresh-assets.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export const version = '5.2.1'
export const publishDates = {
	major: '2026-05-06T16:28:18.473Z',
	minor: '2026-07-01T09:25:08.191Z',
	patch: '2026-07-01T10:33:23.308Z',
}
