export const CONNECTION_CENTER_HANDLE_SIZE_PX = 16
export const CONNECTION_CENTER_HANDLE_HOVER_SIZE_PX = 24

export const NODE_WIDTH_PX = 180
export const NODE_HEADER_HEIGHT_PX = 32.5
export const NODE_ROW_HEIGHT_PX = 32
export const NODE_PORT_OFFSET_Y_PX = 15.5

export const PORT_RADIUS_PX = 6

export const DEFAULT_NODE_SPACING_PX = 60
