main = "src/worker.ts"
compatibility_date = "2024-06-20"

[dev]
port = 8786

[env.dev]
name = "image-optimizer"
services = [{ binding = "SYNC_WORKER", service = "dev-tldraw-multiplayer" }]

[env.staging]
name = "staging-image-optimizer"
services = [{ binding = "SYNC_WORKER", service = "main-tldraw-multiplayer" }]
route = { pattern = "staging-images.tldraw.xyz", custom_domain = true }

[env.production]
name = "image-optimizer"
services = [{ binding = "SYNC_WORKER", service = "tldraw-multiplayer" }]
route = { pattern = "images.tldraw.xyz", custom_domain = true }
