main = "src/worker.ts"
compatibility_date = "2024-06-20"
upload_source_maps = true

#################### Environment names ####################

# Dev environment
[env.dev]
name = "tldraw-consent-dev"

# Staging environment
[env.staging]
name = "tldraw-consent-staging"

# Production environment
[env.production]
name = "tldraw-consent"


#################### Version metadata ####################
[version_metadata]
binding = "CF_VERSION_METADATA"

[env.dev.version_metadata]
binding = "CF_VERSION_METADATA"

[env.preview.version_metadata]
binding = "CF_VERSION_METADATA"

[env.staging.version_metadata]
binding = "CF_VERSION_METADATA"

[env.production.version_metadata]
binding = "CF_VERSION_METADATA"
