name = "shader-template"
compatibility_date = "2025-05-08"
preview_urls = true

[[routes]]
pattern = "shader.templates.tldraw.dev"
custom_domain = true

[observability]
enabled = true

[assets]
directory = "./dist"
