// This file is automatically generated by build-export-css.ts from normalize.css.
// Do not edit manually. Or do, I'm a comment, not a cop.

/*
This file is included in all tldraw SVG exports to help normalize foreign objects. It's based on
modern-normalize, but has some additional rules to help with specific issues we've run into when
working with SVGs. When we create an export, any places where elements are found not to match up
with these defaults will be included on the element in a `style` attribute.

See the bottom of the file for tldraw-specific additions.
*/

/*! modern-normalize v3.0.1 | MIT License | https://github.com/sindresorhus/modern-normalize */

export const normalizeCss =
	'foreignObject *,foreignObject :before,foreignObject :after{box-sizing:border-box}html{font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji";line-height:1.15;-webkit-text-size-adjust:100%;tab-size:4}b,strong{font-weight:bolder}code,kbd,samp,pre{font-family:ui-monospace,SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;font-size:1em}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sub{bottom:-.25em}sup{top:-.5em}table{border-color:currentcolor}button,input,optgroup,select,textarea{font-family:inherit;font-size:100%;line-height:1.15;margin:0}button,[type=button],[type=reset],[type=submit]{-webkit-appearance:button}legend{padding:0}progress{vertical-align:baseline}::-webkit-inner-spin-button,::-webkit-outer-spin-button{height:auto}[type=search]{-webkit-appearance:textfield;outline-offset:-2px}::-webkit-search-decoration{-webkit-appearance:none}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}summary{display:list-item}foreignObject *{border:none 0}\n'
