// The tldraw-coupled collaboration layer. For now it re-exports the commenting package's
// canvas entry point; over time it will re-export the other collaboration packages as well.

export {
	CanvasComments,
	CanvasCommentsSidebar,
	CommentBody,
	CommentTool,
	CommentsFilterMenu,
	CommentsMenuItem,
	CommentsOverflowMenu,
	DEFAULT_IMPRECISE_SHAPE_ANCHOR,
	DEFAULT_SIDEBAR_FILTERS,
	anchorPagePoint,
	collectClusterLeaves,
	commentToolOverrides,
	commentTools,
	commentsHidden,
	computeClusterTable,
	createClusterRuntime,
	focusThread,
	openThreadId,
	pendingComment,
	richTextToPlaintext,
	shapeAnchorAt,
	sidebarFilters,
	toggleCommentsHidden,
	useCommentThreads,
	useComments,
	useCommentingEnabled,
	usePendingComment,
	useThreadComments,
	type CanvasCommentsProps,
	type CanvasCommentsSidebarProps,
	type ClusterNode,
	type ClusterRuntime,
	type ClusterTable,
	type CommentBodyProps,
	type CommentsFilterMenuProps,
	type LeafInput,
	type PendingComment,
	type SidebarFilters,
} from '@tldraw/commenting/canvas'
