name: Issue Triage

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to triage (for testing)'
        required: true
        type: number

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      id-token: write
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get issue details
        id: issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue view ${{ env.ISSUE_NUMBER }} --json title,body,labels,state,author,createdAt > /tmp/issue.json
          echo "details<<EOF" >> $GITHUB_OUTPUT
          cat /tmp/issue.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Search for related issues
        id: related
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get all open issues for similarity comparison
          gh issue list --limit 100 --state open --json number,title,body,labels > /tmp/related-issues.json
          echo "related_issues<<EOF" >> $GITHUB_OUTPUT
          cat /tmp/related-issues.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Enhanced Triage with Claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            You are an enhanced issue triage bot for the tldraw repository. Perform comprehensive triage on issue #${{ env.ISSUE_NUMBER }}.

            ## Issue details
            ```json
            ${{ steps.issue.outputs.details }}
            ```

            ## Related open issues (for duplicate detection)
            ```json
            ${{ steps.related.outputs.related_issues }}
            ```

            ## Triage tasks

            ### 1. Classify the issue type
            Determine if this is a:
            - **Bug**: Something is broken or not working as designed (crashes, rendering errors, data loss)
            - **Improvement**: A request to enhance existing behavior (UX preferences, "I wish X worked like Y")
            - **Feature**: A request for entirely new functionality
            - **Task**: Internal team task
            - **Example**: Request for a new SDK example

            IMPORTANT: Many issues filed as "bugs" are actually improvement requests. A true bug is something objectively broken.

            ### 2. Detect related and duplicate issues
            - Compare the title and description with the related issues provided
            - Look for similar bug reports, related feature requests, or duplicates
            - Identify if this is a clear duplicate (>90% similarity in issue and symptoms)
            - Find related issues that provide useful context (similar area, related feature)

            ### 3. Research affected codebase areas
            Use the codebase exploration tools to:
            - Identify the specific files and functions related to this issue
            - Find relevant test files that might need updates
            - Locate documentation or examples that relate to the issue
            - Provide specific file paths with line numbers when possible

            For bug reports, be especially thorough:
            - Find where the bug is likely occurring
            - Identify related code paths
            - Suggest test cases that should reproduce the issue

            ### 4. Estimate priority
            Analyze and assign a priority based on:
            - **P0 (Critical)**: Data loss, security issues, complete feature breakage affecting all users
            - **P1 (High)**: Significant functionality broken, affects many users, no workaround
            - **P2 (Medium)**: Functionality impaired but has workaround, affects some users
            - **P3 (Low)**: Minor issues, nice-to-have improvements, affects few users

            Consider:
            - How many users are likely affected?
            - Is there a workaround?
            - Does this block other work?
            - Is this a regression or long-standing issue?

            ### 5. Apply labels
            Add appropriate labels using `gh issue edit --add-label`:

            **Area labels:**
            - `sdk` - Affects @tldraw/tldraw package
            - `dotcom` - Related to tldraw.com
            - `docs` - Documentation changes
            - `examples` - SDK example requests
            - `performance` - Performance issues
            - `a11y` - Accessibility issues

            **Type labels:**
            - `bugfix` - Confirmed bugs (use only for TRUE bugs)
            - `feature` - New features
            - `improvement` - Product improvements (use this for UX preferences)

            **Priority labels:**
            - `P0` - Critical priority
            - `P1` - High priority
            - `P2` - Medium priority
            - `P3` - Low priority

            **Status labels:**
            - `More Info Needed` - Issue lacks critical info to understand/reproduce
            - `duplicate` - Clear duplicate of another issue

            ### 6. Suggest milestone (comment only, don't assign)
            Based on the priority and issue type, suggest which milestone this should be in:
            - P0/P1 bugs → Current sprint milestone
            - P2 bugs → Next sprint milestone
            - Features → Roadmap milestone or backlog

            Note: Only suggest in your comment, do not use gh CLI to assign milestones.

            ## Output format

            Post a comprehensive triage comment using `gh issue comment` with this structure:

            ```markdown
            ## Triage summary
            - **Type**: [Bug|Feature|Improvement|Task|Example]
            - **Priority**: [P0|P1|P2|P3] - [Brief justification]
            - **Area**: [Specific subsystem, e.g., "Editor → Selection → Arrow bindings"]
            - **Affected users**: [Estimate: All|Many|Some|Few]
            - **Workaround available**: [Yes|No|Partial]

            ## Related issues
            [If any duplicates or related issues found, list them with links and brief descriptions]
            - Possible duplicate: #XXXX - [Brief description of similarity]
            - Related: #YYYY - [How it relates]
            - See also: #ZZZZ - [Additional context]

            [If this is a clear duplicate:]
            **🔄 This appears to be a duplicate of #XXXX**

            ## Affected code
            [Based on codebase research, list relevant files and functions]
            - `path/to/file.ts:123` - [Description of relevance]
            - `path/to/tests.test.ts` - [Related test file]

            ## For bug reports: Reproduction analysis
            [If this is a bug, analyze the reproduction steps]
            - **Reproduction**: [Clear|Needs more info|Cannot reproduce]
            - **Root cause hypothesis**: [Your analysis of what might be wrong]
            - **Suggested investigation**: [Where to start debugging]

            ## Implementation guidance
            [For features/improvements, suggest approach]
            1. [Step 1]
            2. [Step 2]
            3. [Step 3]

            ## Suggested milestone
            [Your milestone recommendation with reasoning]

            ## For implementing agents
            [Structured brief to help future AI agents or developers pick this up]
            - **Ready for implementation**: [Yes|Needs design|Needs more info]
            - **Key files to modify**: [List]
            - **Test strategy**: [What tests to add/modify]
            - **Documentation impact**: [Yes|No - what needs updating]

            ---
            *🤖 Automated triage by Claude Code*
            ```

            ## Execution steps

            1. **Analyze the issue** - Read and understand the request
            2. **Detect duplicates** - Compare with related issues, identify clear duplicates
            3. **Research codebase** - Use Glob, Grep, and Read to find relevant code
            4. **Classify and prioritize** - Determine type and priority
            5. **Apply labels** - Use `gh issue edit --add-label "label1,label2,label3"` to add all labels at once
            6. **Post triage comment** - Use `gh issue comment` to post the comprehensive analysis
            7. **Handle duplicates** - If this is a clear duplicate, add a comment suggesting closure and linking to the original

            ## Special handling

            **For clear duplicates:**
            - Add the `duplicate` label
            - Post a comment like: "This issue appears to be a duplicate of #XXXX. Please continue the discussion there. Closing as duplicate."
            - Close the issue with: `gh issue close ${{ env.ISSUE_NUMBER }} --reason duplicate --comment "Duplicate of #XXXX"`

            **For issues needing more info:**
            - Add the `More Info Needed` label
            - In your comment, specifically list what information is missing
            - Suggest what the user should provide (reproduction steps, environment details, screenshots, etc.)

            IMPORTANT: Always post your comprehensive triage comment. This is crucial for maintainers and future implementing agents.
          claude_args: '--allowedTools "Bash(gh issue:*),Bash(gh api:*),Read,Glob,Grep,Task,Write,WebSearch"'
