#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

# This notifies the user if the yarn.lock file has changed.
CHANGED=$(git diff HEAD@{1} --stat -- ./yarn.lock | wc -l)
if (( CHANGED > 0 )); then
    echo
    echo "🚨 🚨 🚨 yarn.lock has changed! 🚨 🚨 🚨 "
    echo "run 'yarn' to get the latest!"
    echo
fi

command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-merge' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
git lfs post-merge "$@"
