#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

# This notifies the user if the yarn.lock file has changed.
CHANGED=$(git diff HEAD@{1} --stat -- ./yarn.lock | wc -l)
if (( CHANGED > 0 )); then
    echo
    echo "🚨 🚨 🚨 yarn.lock has changed! 🚨 🚨 🚨 "
    echo "run 'yarn' to get the latest!"
    echo
fi
