#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

# This notifies the user if the pnpm-lock.yaml file has changed.
CHANGED=$(git diff HEAD@{1} --stat -- ./pnpm-lock.yaml | wc -l)
if (( CHANGED > 0 )); then
    echo
    echo "🚨 🚨 🚨 pnpm-lock.yaml has changed! 🚨 🚨 🚨 "
    echo "run 'pnpm i' to get the latest!"
    echo
fi
