name = "fairydraw"
main = "worker.ts"
compatibility_date = "2024-12-30"
assets = { not_found_handling = "single-page-application" }
preview_urls = true

[observability]
enabled = true

[[routes]]
pattern = "agent.templates.tldraw.dev"
custom_domain = true

# Set up the durable object used for each tldraw room
[durable_objects]
bindings = [
    { name = "AGENT_DURABLE_OBJECT", class_name = "AgentDurableObject" },
]

# Durable objects require migrations to create/modify/delete them
[[migrations]]
tag = "v1"
new_classes = ["TldrawAiDurableObject"]

[[migrations]]
tag = "v2"
renamed_classes = [
    { from = "TldrawAiDurableObject", to = "AgentDurableObject" },
]
