name: Deploy docs when a release is edited

on:
  release:
    types: [edited]

jobs:
  deploy:
    name: Deploy docs on release edit
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy webhook
        run: curl -X POST "$VERCEL_DOCS_DEPLOY_WEBHOOK_URL"
        env:
          VERCEL_DOCS_DEPLOY_WEBHOOK_URL: ${{ secrets.VERCEL_DOCS_DEPLOY_WEBHOOK_URL }}
