name: Get draft changelog

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  deploy:
    name: 'Get draft changlog'
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Run our setup
        uses: ./.github/actions/setup

      - name: Extract changelog
        run: yarn extract-draft-changelog

      - name: Upload changelog.md to artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: changelog-output
          path: changelog.md
