name: Publish branch packages

on:
  pull_request:
    types: [labeled]

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  remove-label:
    name: Remove the publish-packages label
    if: github.event.label.name == 'publish-packages'
    runs-on: ubuntu-latest
    steps:
      - name: Remove the publish-packages label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: publish-packages

  publish:
    name: 'Publish branch packages'
    if: github.event.label.name == 'publish-packages'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-npm.yml
    with:
      publish-command: yarn tsx ./internal/scripts/publish-prerelease.ts internal
      bemo-url: https://canary-demo.tldraw.xyz

  comment:
    name: Tell user released version
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Tell user released version
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Published version ${{ needs.publish.outputs.version }} to npm.
