name: Publish VS Code Extension

on:
  push:
    branches:
      - main
      - production

env:
  CI: 1
  PRINT_GITHUB_ANNOTATIONS: 1
defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish VS Code Extension
    environment: vsce publish
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/setup

      - name: Build types
        run: yarn build-types

      - name: Get extension info from the marketplace
        working-directory: 'apps/vscode/extension'
        run: yarn get-info

      - name: Publish extension
        run: yarn tsx ./internal/scripts/publish-vscode-extension.ts
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          TLDRAW_ENV: ${{ (github.ref == 'refs/heads/production' && 'production') || (github.ref == 'refs/heads/main' && 'staging') }}
