name: Publish Prerelease Packages

on:
  push:
    branches: [main, production]

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: 'Publish Prerelease Packages'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-npm.yml
    with:
      publish-command: yarn tsx ./internal/scripts/publish-prerelease.ts ${{ github.ref == 'refs/heads/production' && 'next' || 'canary' }}
      bemo-url: https://canary-demo.tldraw.xyz

  notify-tldraw-desktop:
    name: Notify tldraw-desktop
    if: github.ref == 'refs/heads/production'
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.HUPPY_APP_ID }}
          private-key: ${{ secrets.HUPPY_PRIVATE_KEY }}
          owner: tldraw
          repositories: tldraw-desktop

      - name: Notify tldraw-desktop
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            https://api.github.com/repos/tldraw/tldraw-desktop/dispatches \
            -d '{"event_type":"tldraw-release","client_payload":{"version":"${{ needs.publish.outputs.version }}","tag":"next"}}'
