name: (Re)Publish SDK packages manually
# This only attempts to publish the public packages to npm.
# It does not bump the version, it does not update the changelogs, it does not create a github release.

# Prevent more than one non-canary npm publishing job from running at the same time
concurrency:
  group: npm-publish

# Package publishing is manually triggered on github actions dashboard
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true
        default: e.g. 3.12.1

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: '(Re)Publish public packages manually'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-npm.yml
    with:
      publish-command: yarn tsx ./internal/scripts/publish-manual.ts
      bemo-url: https://demo.tldraw.xyz
      version-string: ${{ inputs.version }}

  publish_templates:
    name: Publishes code templates to separate repositories
    uses: tldraw/tldraw/.github/workflows/publish-templates.yml@main
    if: ${{ needs.publish.outputs.is_latest_version == 'true' }}
    secrets:
      HUPPY_PRIVATE_KEY: ${{ secrets.HUPPY_PRIVATE_KEY }}
      HUPPY_APP_ID: ${{ vars.HUPPY_APP_ID }}
      DISCORD_DEPLOY_WEBHOOK_URL: ${{ secrets.DISCORD_DEPLOY_WEBHOOK_URL }}
    needs: publish
